apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: api
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
